export const emojiObj = {
    "[微笑]": "pet_emoji_0",
    "[撇嘴]": "pet_emoji_1",
    "[色]": "pet_emoji_2",
    "[发呆]": "pet_emoji_3",
    "[得意]": "pet_emoji_4",
    "[流泪]": "pet_emoji_5",
    "[害羞]": "pet_emoji_6",
    "[闭嘴]": "pet_emoji_7",
    "[睡]": "pet_emoji_8",
    "[大哭]": "pet_emoji_9",
    "[尴尬]": "pet_emoji_10",
    "[发怒]": "pet_emoji_11",
    "[调皮]": "pet_emoji_12",
    "[呲牙]": "pet_emoji_13",
    "[惊讶]": "pet_emoji_14",
    "[难过]": "pet_emoji_15",
    "[酷]": "pet_emoji_16",
    "[冷汗]": "pet_emoji_17",
    "[抓狂]": "pet_emoji_18",
    "[吐]": "pet_emoji_19",
    "[偷笑]": "pet_emoji_20",
    "[愉快]": "pet_emoji_21",
    "[白眼]": "pet_emoji_22",
    "[傲慢]": "pet_emoji_23",
    "[饥饿]": "pet_emoji_24",
    "[困]": "pet_emoji_25",
    "[惊恐]": "pet_emoji_26",
    "[流汗]": "pet_emoji_27",
    "[憨笑]": "pet_emoji_28",
    "[悠闲]": "pet_emoji_29",
    "[奋斗]": "pet_emoji_30",
    "[咒骂]": "pet_emoji_31",
    "[疑问]": "pet_emoji_32",
    "[嘘]": "pet_emoji_33",
    "[晕]": "pet_emoji_34",
    "[折磨]": "pet_emoji_35",
    "[衰]": "pet_emoji_36",
    "[骷髅]": "pet_emoji_37",
    "[敲打]": "pet_emoji_38",
    "[再见]": "pet_emoji_39",
    "[擦汗]": "pet_emoji_40",
    "[抠鼻]": "pet_emoji_41",
    "[鼓掌]": "pet_emoji_42",
    "[糗大了]": "pet_emoji_43",
    "[坏笑]": "pet_emoji_44",
    "[左哼哼]": "pet_emoji_45",
    "[右哼哼]": "pet_emoji_46",
    "[哈欠]": "pet_emoji_47",
    "[鄙视]": "pet_emoji_48",
    "[委屈]": "pet_emoji_49",
    "[快哭了]": "pet_emoji_50",
    "[阴险]": "pet_emoji_51",
    "[亲亲]": "pet_emoji_52",
    "[吓]": "pet_emoji_53",
    "[可怜]": "pet_emoji_54",
    "[菜刀]": "pet_emoji_55",
    "[西瓜]": "pet_emoji_56",
    "[啤酒]": "pet_emoji_57",
    "[篮球]": "pet_emoji_58",
    "[乒乓]": "pet_emoji_59",
    "[咖啡]": "pet_emoji_60",
    "[饭]": "pet_emoji_61",
    "[猪头]": "pet_emoji_62",
    "[玫瑰]": "pet_emoji_63",
    "[凋谢]": "pet_emoji_64",
    "[嘴唇]": "pet_emoji_65",
    "[爱心]": "pet_emoji_66",
    "[心碎]": "pet_emoji_67",
    "[蛋糕]": "pet_emoji_68",
    "[闪电]": "pet_emoji_69",
    "[炸弹]": "pet_emoji_70",
    "[刀]": "pet_emoji_71",
    "[足球]": "pet_emoji_72",
    "[瓢虫]": "pet_emoji_73",
    "[便便]": "pet_emoji_74",
    "[月亮]": "pet_emoji_75",
    "[太阳]": "pet_emoji_76",
    "[礼物]": "pet_emoji_77",
    "[拥抱]": "pet_emoji_78",
    "[强]": "pet_emoji_79",
    "[弱]": "pet_emoji_80",
    "[握手]": "pet_emoji_81",
    "[胜利]": "pet_emoji_82",
    "[抱拳]": "pet_emoji_83",
    "[勾引]": "pet_emoji_84",
    "[拳头]": "pet_emoji_85",
    "[差劲]": "pet_emoji_86",
    "[爱你]": "pet_emoji_87",
    "[NO]": "pet_emoji_88",
    "[OK]": "pet_emoji_89",
    "[双喜]": "pet_emoji_90",
    "[鞭炮]": "pet_emoji_91",
    "[灯笼]": "pet_emoji_92",
    "[话筒]": "pet_emoji_93",
    "[庆祝]": "pet_emoji_94",
    "[香蕉]": "pet_emoji_95",
    "[爆筋]": "pet_emoji_96",
    "[棒棒糖]": "pet_emoji_97",
    "[奶瓶]": "pet_emoji_98",
    "[飞机]": "pet_emoji_99",
    "[汽车]": "pet_emoji_100",
    "[高铁]": "pet_emoji_101",
    "[枪]": "pet_emoji_102",
    "[气球]": "pet_emoji_103",
    "[邮件]": "pet_emoji_104",
    "[熊猫]": "pet_emoji_105",
    "[青蛙]": "pet_emoji_106",
    "[灯泡]": "pet_emoji_107",
    "[雨伞]": "pet_emoji_108",
    "[象棋]": "pet_emoji_109",
    "[麻将]": "pet_emoji_110",
    "[钱]": "pet_emoji_111",
    "[吃面]": "pet_emoji_112",
    "[闹钟]": "pet_emoji_113",
    "[药丸]": "pet_emoji_114",
    "[多云]": "pet_emoji_115",
    "[下雨]": "pet_emoji_116",
    "[纸巾]": "pet_emoji_117",
    "[风车]": "pet_emoji_118",
    "[沙发]": "pet_emoji_119",
    "[祈祷]": "pet_emoji_120",
    "[得]": "pet_emoji_121",
    "[秘]": "pet_emoji_122",
    "[祝]": "pet_emoji_123",
    "[合]": "pet_emoji_124",
    "[满]": "pet_emoji_125",
    "[割]": "pet_emoji_126",
    "[禁]": "pet_emoji_127",
    "[A]": "pet_emoji_128",
};

export const emojiObjText = {
    pet_emoji_0: "[微笑]",
    pet_emoji_1: "[撇嘴]",
    pet_emoji_2: "[色]",
    pet_emoji_3: "[发呆]",
    pet_emoji_4: "[得意]",
    pet_emoji_5: "[流泪]",
    pet_emoji_6: "[害羞]",
    pet_emoji_7: "[闭嘴]",
    pet_emoji_8: "[睡]",
    pet_emoji_9: "[大哭]",
    pet_emoji_10: "[尴尬]",
    pet_emoji_11: "[发怒]",
    pet_emoji_12: "[调皮]",
    pet_emoji_13: "[呲牙]",
    pet_emoji_14: "[惊讶]",
    pet_emoji_15: "[难过]",
    pet_emoji_16: "[酷]",
    pet_emoji_17: "[冷汗]",
    pet_emoji_18: "[抓狂]",
    pet_emoji_19: "[吐]",
    pet_emoji_20: "[偷笑]",
    pet_emoji_21: "[愉快]",
    pet_emoji_22: "[白眼]",
    pet_emoji_23: "[傲慢]",
    pet_emoji_24: "[饥饿]",
    pet_emoji_25: "[困]",
    pet_emoji_26: "[惊恐]",
    pet_emoji_27: "[流汗]",
    pet_emoji_28: "[憨笑]",
    pet_emoji_29: "[悠闲]",
    pet_emoji_30: "[奋斗]",
    pet_emoji_31: "[咒骂]",
    pet_emoji_32: "[疑问]",
    pet_emoji_33: "[嘘]",
    pet_emoji_34: "[晕]",
    pet_emoji_35: "[折磨]",
    pet_emoji_36: "[衰]",
    pet_emoji_37: "[骷髅]",
    pet_emoji_38: "[敲打]",
    pet_emoji_39: "[再见]",
    pet_emoji_40: "[擦汗]",
    pet_emoji_41: "[抠鼻]",
    pet_emoji_42: "[鼓掌]",
    pet_emoji_43: "[糗大了]",
    pet_emoji_44: "[坏笑]",
    pet_emoji_45: "[左哼哼]",
    pet_emoji_46: "[右哼哼]",
    pet_emoji_47: "[哈欠]",
    pet_emoji_48: "[鄙视]",
    pet_emoji_49: "[委屈]",
    pet_emoji_50: "[快哭了]",
    pet_emoji_51: "[阴险]",
    pet_emoji_52: "[亲亲]",
    pet_emoji_53: "[吓]",
    pet_emoji_54: "[可怜]",
    pet_emoji_55: "[菜刀]",
    pet_emoji_56: "[西瓜]",
    pet_emoji_57: "[啤酒]",
    pet_emoji_58: "[篮球]",
    pet_emoji_59: "[乒乓]",
    pet_emoji_60: "[咖啡]",
    pet_emoji_61: "[饭]",
    pet_emoji_62: "[猪头]",
    pet_emoji_63: "[玫瑰]",
    pet_emoji_64: "[凋谢]",
    pet_emoji_65: "[嘴唇]",
    pet_emoji_66: "[爱心]",
    pet_emoji_67: "[心碎]",
    pet_emoji_68: "[蛋糕]",
    pet_emoji_69: "[闪电]",
    pet_emoji_70: "[炸弹]",
    pet_emoji_71: "[刀]",
    pet_emoji_72: "[足球]",
    pet_emoji_73: "[瓢虫]",
    pet_emoji_74: "[便便]",
    pet_emoji_75: "[月亮]",
    pet_emoji_76: "[太阳]",
    pet_emoji_77: "[礼物]",
    pet_emoji_78: "[拥抱]",
    pet_emoji_79: "[强]",
    pet_emoji_80: "[弱]",
    pet_emoji_81: "[握手]",
    pet_emoji_82: "[胜利]",
    pet_emoji_83: "[抱拳]",
    pet_emoji_84: "[勾引]",
    pet_emoji_85: "[拳头]",
    pet_emoji_86: "[差劲]",
    pet_emoji_87: "[爱你]",
    pet_emoji_88: "[NO]",
    pet_emoji_89: "[OK]",
    pet_emoji_90: "[双喜]",
    pet_emoji_91: "[鞭炮]",
    pet_emoji_92: "[灯笼]",
    pet_emoji_93: "[话筒]",
    pet_emoji_94: "[庆祝]",
    pet_emoji_95: "[香蕉]",
    pet_emoji_96: "[爆筋]",
    pet_emoji_97: "[棒棒糖]",
    pet_emoji_98: "[奶瓶]",
    pet_emoji_99: "[飞机]",
    pet_emoji_100: "[汽车]",
    pet_emoji_101: "[高铁]",
    pet_emoji_102: "[枪]",
    pet_emoji_103: "[气球]",
    pet_emoji_104: "[邮件]",
    pet_emoji_105: "[熊猫]",
    pet_emoji_106: "[青蛙]",
    pet_emoji_107: "[灯泡]",
    pet_emoji_108: "[雨伞]",
    pet_emoji_109: "[象棋]",
    pet_emoji_110: "[麻将]",
    pet_emoji_111: "[钱]",
    pet_emoji_112: "[吃面]",
    pet_emoji_113: "[闹钟]",
    pet_emoji_114: "[药丸]",
    pet_emoji_115: "[多云]",
    pet_emoji_116: "[下雨]",
    pet_emoji_117: "[纸巾]",
    pet_emoji_118: "[风车]",
    pet_emoji_119: "[沙发]",
    pet_emoji_120: "[祈祷]",
    pet_emoji_121: "[得]",
    pet_emoji_122: "[秘]",
    pet_emoji_123: "[祝]",
    pet_emoji_124: "[合]",
    pet_emoji_125: "[满]",
    pet_emoji_126: "[割]",
    pet_emoji_127: "[禁]",
    pet_emoji_128: "[A]",
};

export const emojiTextList = [
    "[微笑]",
    "[撇嘴]",
    "[色]",
    "[发呆]",
    "[得意]",
    "[流泪]",
    "[害羞]",
    "[闭嘴]",
    "[睡]",
    "[大哭]",
    "[尴尬]",
    "[发怒]",
    "[调皮]",
    "[呲牙]",
    "[惊讶]",
    "[难过]",
    "[酷]",
    "[冷汗]",
    "[抓狂]",
    "[吐]",
    "[偷笑]",
    "[愉快]",
    "[白眼]",
    "[傲慢]",
    "[饥饿]",
    "[困]",
    "[惊恐]",
    "[流汗]",
    "[憨笑]",
    "[悠闲]",
    "[奋斗]",
    "[咒骂]",
    "[疑问]",
    "[嘘]",
    "[晕]",
    "[折磨]",
    "[衰]",
    "[骷髅]",
    "[敲打]",
    "[再见]",
    "[擦汗]",
    "[抠鼻]",
    "[鼓掌]",
    "[糗大了]",
    "[坏笑]",
    "[左哼哼]",
    "[右哼哼]",
    "[哈欠]",
    "[鄙视]",
    "[委屈]",
    "[快哭了]",
    "[阴险]",
    "[亲亲]",
    "[吓]",
    "[可怜]",
    "[菜刀]",
    "[西瓜]",
    "[啤酒]",
    "[篮球]",
    "[乒乓]",
    "[咖啡]",
    "[饭]",
    "[猪头]",
    "[玫瑰]",
    "[凋谢]",
    "[嘴唇]",
    "[爱心]",
    "[心碎]",
    "[蛋糕]",
    "[闪电]",
    "[炸弹]",
    "[刀]",
    "[足球]",
    "[瓢虫]",
    "[便便]",
    "[月亮]",
    "[太阳]",
    "[礼物]",
    "[拥抱]",
    "[强]",
    "[弱]",
    "[握手]",
    "[胜利]",
    "[抱拳]",
    "[勾引]",
    "[拳头]",
    "[差劲]",
    "[爱你]",
    "[NO]",
    "[OK]",
    "[双喜]",
    "[鞭炮]",
    "[灯笼]",
    "[话筒]",
    "[庆祝]",
    "[香蕉]",
    "[爆筋]",
    "[棒棒糖]",
    "[奶瓶]",
    "[飞机]",
    "[汽车]",
    "[高铁]",
    "[枪]",
    "[气球]",
    "[邮件]",
    "[熊猫]",
    "[青蛙]",
    "[灯泡]",
    "[雨伞]",
    "[象棋]",
    "[麻将]",
    "[钱]",
    "[吃面]",
    "[闹钟]",
    "[药丸]",
    "[多云]",
    "[下雨]",
    "[纸巾]",
    "[风车]",
    "[沙发]",
    "[祈祷]",
    "[得]",
    "[秘]",
    "[祝]",
    "[合]",
    "[满]",
    "[割]",
    "[禁]",
    "[A]",
];
