// ─── Client → Server ───

pub const LOGIN: u16 = 10001;
pub const LOGOUT: u16 = 10002;
pub const SEND_PRIVATE_MSG: u16 = 10101;
pub const RECALL_PRIVATE_MSG: u16 = 10105;
pub const SEND_RECEIPT: u16 = 10106;
pub const SEND_GROUP_MSG: u16 = 10201;
pub const RECALL_GROUP_MSG: u16 = 10205;
pub const GROUP_EVENT_RECEIPT: u16 = 10210;
pub const KEY_PAIR_RECEIVED: u16 = 10501;
pub const HEARTBEAT: u16 = 19901;
pub const ACK_SERVER_MSG: u16 = 19902;
pub const SEND_CHANNEL_MSG: u16 = 4101;
pub const RECALL_CHANNEL_MSG: u16 = 4102;
pub const READ_CHANNEL_MSG: u16 = 4103;

// ─── Server → Client ───

pub const LOGIN_RESP: u16 = 20001;
pub const LOGOUT_RESP: u16 = 20002;
pub const FORCE_LOGOUT: u16 = 20003;
pub const PRIVATE_MSG_SENT: u16 = 20101;
pub const PRIVATE_MSG_RECEIVED: u16 = 20102;
pub const PRIVATE_MSG_RECALLED: u16 = 20103;
pub const RECEIPT_PUSH: u16 = 20104;
pub const GROUP_MSG_SENT: u16 = 20201;
pub const GROUP_MSG_RECEIVED: u16 = 20202;
pub const GROUP_MSG_RECALLED: u16 = 20203;
pub const FRIEND_RECORD_PUSH: u16 = 20301;
pub const FRIEND_REQ_NUM_PUSH: u16 = 20302;
pub const GROUP_REQ_NUM_PUSH: u16 = 20401;
pub const GROUP_REQ_MSG_PUSH: u16 = 20402;
pub const GROUP_READ_RECEIPT_PUSH: u16 = 20403;
pub const KEY_PAIR_CHANGE_PUSH: u16 = 20501;
pub const USER_ONLINE_STATUS_PUSH: u16 = 20601;
pub const GROUP_EVENT_PUSH: u16 = 20701;
// 群直播打赏/礼物推送，旧 im 只展示临时气泡，不作为聊天消息落库。
pub const GROUP_LIVE_SEND_GIFT_PUSH: u16 = 2217;
pub const HEARTBEAT_RESP: u16 = 29901;
pub const ERROR_RESP: u16 = 29999;
pub const SENSITIVE_WORDS_PUSH: u16 = 30001;
pub const CHANNEL_MSG_SENT: u16 = 4201;
pub const CHANNEL_MSG_RECEIVED: u16 = 4203;
pub const CHANNEL_EVENT_PUSH: u16 = 4204;
pub const CHANNEL_MSG_RECALLED: u16 = 4205;
pub const CHANNEL_READ_PUSH: u16 = 4206;

/// Return a human-readable name for a command code (useful for logging).
pub fn cmd_name(cmd: u16) -> &'static str {
    match cmd {
        LOGIN => "LOGIN",
        LOGOUT => "LOGOUT",
        SEND_PRIVATE_MSG => "SEND_PRIVATE_MSG",
        RECALL_PRIVATE_MSG => "RECALL_PRIVATE_MSG",
        SEND_RECEIPT => "SEND_RECEIPT",
        SEND_GROUP_MSG => "SEND_GROUP_MSG",
        RECALL_GROUP_MSG => "RECALL_GROUP_MSG",
        GROUP_EVENT_RECEIPT => "GROUP_EVENT_RECEIPT",
        KEY_PAIR_RECEIVED => "KEY_PAIR_RECEIVED",
        HEARTBEAT => "HEARTBEAT",
        ACK_SERVER_MSG => "ACK_SERVER_MSG",
        SEND_CHANNEL_MSG => "SEND_CHANNEL_MSG",
        RECALL_CHANNEL_MSG => "RECALL_CHANNEL_MSG",
        READ_CHANNEL_MSG => "READ_CHANNEL_MSG",
        LOGIN_RESP => "LOGIN_RESP",
        LOGOUT_RESP => "LOGOUT_RESP",
        FORCE_LOGOUT => "FORCE_LOGOUT",
        PRIVATE_MSG_SENT => "PRIVATE_MSG_SENT",
        PRIVATE_MSG_RECEIVED => "PRIVATE_MSG_RECEIVED",
        PRIVATE_MSG_RECALLED => "PRIVATE_MSG_RECALLED",
        RECEIPT_PUSH => "RECEIPT_PUSH",
        GROUP_MSG_SENT => "GROUP_MSG_SENT",
        GROUP_MSG_RECEIVED => "GROUP_MSG_RECEIVED",
        GROUP_MSG_RECALLED => "GROUP_MSG_RECALLED",
        FRIEND_RECORD_PUSH => "FRIEND_RECORD_PUSH",
        FRIEND_REQ_NUM_PUSH => "FRIEND_REQ_NUM_PUSH",
        GROUP_REQ_NUM_PUSH => "GROUP_REQ_NUM_PUSH",
        GROUP_REQ_MSG_PUSH => "GROUP_REQ_MSG_PUSH",
        GROUP_READ_RECEIPT_PUSH => "GROUP_READ_RECEIPT_PUSH",
        KEY_PAIR_CHANGE_PUSH => "KEY_PAIR_CHANGE_PUSH",
        USER_ONLINE_STATUS_PUSH => "USER_ONLINE_STATUS_PUSH",
        GROUP_EVENT_PUSH => "GROUP_EVENT_PUSH",
        GROUP_LIVE_SEND_GIFT_PUSH => "GROUP_LIVE_SEND_GIFT_PUSH",
        HEARTBEAT_RESP => "HEARTBEAT_RESP",
        ERROR_RESP => "ERROR_RESP",
        SENSITIVE_WORDS_PUSH => "SENSITIVE_WORDS_PUSH",
        CHANNEL_MSG_SENT => "CHANNEL_MSG_SENT",
        CHANNEL_MSG_RECEIVED => "CHANNEL_MSG_RECEIVED",
        CHANNEL_EVENT_PUSH => "CHANNEL_EVENT_PUSH",
        CHANNEL_MSG_RECALLED => "CHANNEL_MSG_RECALLED",
        CHANNEL_READ_PUSH => "CHANNEL_READ_PUSH",
        _ => "UNKNOWN",
    }
}
